baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Max Verigin"
theme = "sigsegv-minimal"

# Allowlist approach: only mount processed photos, never source photos
[[module.mounts]]
  source = "static/photography/dist"
  target = "static/photography/dist"

[params]
  description = "Software Developer & Photographer"
  darkMode = true
  software_dev_start_year = 2011
  github_url = "https://github.com/sigseg1v"
  software_dev_teamlead_start_year = 2017

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "Experience"
  url = "/experience/"
  weight = 2

[[menus.main]]
  name = "Photography"
  url = "/photography/"
  weight = 3

[[menus.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4
